"""MongoDB collection names. Multi-word names use snake_case."""

BRANCHES = "branches"
CUSTOMERS = "customers"
INVOICES = "invoices"
INVOICE_DETAILS = "invoice_details"
PICKUPS = "pickups"
CONTAINERS = "containers"
DELIVERIES = "deliveries"
EMPLOYEES = "employees"
USERS = "users"
COUNTERS = "counters"
ACCOUNTS = "accounts"
INCOME_STATEMENTS = "income_statements"
ROLES = "roles"
PERMISSIONS = "permissions"
CITIES = "cities"
ACTIVITY_LOGS = "activity_logs"
JOURNALS = "journals"
